import React, { FormEvent, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BriefcaseBusiness, CalendarDays, ChevronDown, ChevronUp, Heart, Mail, Search, ShieldCheck, Users, X } from 'lucide-react'
import './styles.css'

const api = async (path: string, options: RequestInit = {}) => {
  const r = await fetch(`/api${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options })
  if (!r.ok) throw new Error((await r.json().catch(() => ({}))).detail || 'Something went wrong')
  return r.json()
}
type User = { id:number; name:string; email?:string|null; graduation_year?:number; branch?:string; company?:string; title?:string; location?:string; bio?:string; skills?:string; linkedin?:string; role?:string }
type Job = {id:number; title:string; description:string; company:string; location:string; apply_url?:string}
type Event = {id:number; title:string; description:string; venue:string; starts_at:string}
type RazorpayResponse = { razorpay_order_id:string; razorpay_payment_id:string; razorpay_signature:string }

declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void } } }

const loadRazorpayCheckout = () => new Promise<void>((resolve, reject) => {
  if (window.Razorpay) return resolve()
  const script = document.createElement('script')
  script.src = 'https://checkout.razorpay.com/v1/checkout.js'
  script.async = true
  script.onload = () => resolve()
  script.onerror = () => reject(new Error('Unable to load Razorpay Checkout. Check your internet connection and try again.'))
  document.head.appendChild(script)
})

function App() {
  const [page, setPage] = useState('home'), [user, setUser] = useState<User | null>(null)
  const [alumni, setAlumni] = useState<User[]>([]), [jobs, setJobs] = useState<Job[]>([]), [events, setEvents] = useState<Event[]>([])
  const [modal, setModal] = useState<User | null>(null), [notice, setNotice] = useState('')
  const load = async () => { setAlumni(await api('/alumni')); setJobs(await api('/jobs')); setEvents(await api('/events')); try { setUser(await api('/me')) } catch { setUser(null) } }
  useEffect(() => { load().catch(e => setNotice(e.message)) }, [])
  const nav = (p:string) => { setPage(p); window.scrollTo(0,0) }
  const logout = async () => { await api('/auth/logout',{method:'POST'}); setUser(null); nav('home') }
  return <><header><button className="brand" onClick={()=>nav('home')}><span>TSEC</span> Alumni Connect</button><nav>{['Directory','Jobs','Events','Donate'].map(x=><button key={x} onClick={()=>nav(x.toLowerCase())}>{x}</button>)}{user?.role==='admin'&&<button onClick={()=>nav('admin')}>Admin</button>}</nav>{user?<div className="account"><small>{user.name}</small><button className="ghost" onClick={logout}>Sign out</button></div>:<button className="sign" onClick={()=>nav('signin')}>Sign in</button>}</header>
  {notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  <main>{page==='home'&&<Home nav={nav}/>} {page==='directory'&&<Directory alumni={alumni} user={user} open={setModal}/>} {page==='jobs'&&<Jobs jobs={jobs} user={user} done={load}/>} {page==='events'&&<Events events={events} user={user} done={load}/>} {page==='donate'&&<Donate user={user} note={setNotice}/>} {page==='signin'&&<SignIn after={async()=>{await load();nav('directory')}}/>} {page==='admin'&&<Admin user={user} done={load} note={setNotice}/>}</main>
  <footer>Thadomal Shahani Engineering College · Alumni Connect · Built for the TSEC community</footer>
  {modal&&<ContactModal person={modal} user={user} close={()=>setModal(null)} note={setNotice}/>}</>
}

const Home=({nav}:{nav:(x:string)=>void})=><><section className="hero"><p className="eyebrow">THADOMAL SHAHANI ENGINEERING COLLEGE</p><h1>Your TSEC network,<br/><em>always within reach.</em></h1><p className="lead">Meet alumni, discover opportunities, return to campus, and invest in the students who follow you.</p><div className="actions"><button className="primary" onClick={()=>nav('directory')}>Explore the directory</button><button className="secondary" onClick={()=>nav('signin')}>Join the community</button></div><div className="metrics"><b>3,500+<small>Alumni network</small></b><b>40+<small>Years of impact</small></b><b>1<small>Shared community</small></b></div></section><section className="features">{[[Users,'Find your people','Reconnect with batchmates and meet mentors across industries.'],[BriefcaseBusiness,'Build your career','Discover opportunities shared by the TSEC community.'],[CalendarDays,'Come together','Never miss a reunion, workshop, or campus event.'],[Heart,'Give forward','Support the next generation of TSEC engineers.']].map(([I,t,d]:any)=><article key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</section></>

function Directory({alumni,user,open}:{alumni:User[],user:User|null,open:(p:User)=>void}) { const [q,setQ]=useState(''); const rows=alumni.filter(x=>`${x.name} ${x.company} ${x.skills} ${x.branch}`.toLowerCase().includes(q.toLowerCase())); return <section className="page"><p className="eyebrow">ALUMNI DIRECTORY</p><h2>Find your next conversation.</h2><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, company, skill, or branch"/></div><div className="cards">{rows.map(a=><article className="person" key={a.id}><div className="avatar">{a.name.split(' ').map(n=>n[0]).join('')}</div><div><h3>{a.name}</h3><p>{a.title} {a.company&&`at ${a.company}`}</p><small>{a.branch} · {a.graduation_year} · {a.location}</small>{a.skills&&<div className="tags">{a.skills.split(',').slice(0,3).map(s=><span key={s}>{s.trim()}</span>)}</div>}<button className="link" onClick={()=>open(a)}>{user?.role==='verified'||user?.role==='admin'?'Connect':'View profile'}</button></div></article>)}</div></section> }

function Jobs({jobs,user,done}:{jobs:Job[],user:User|null,done:()=>Promise<void>}) { return <section className="page"><p className="eyebrow">OPPORTUNITIES</p><h2>Build what comes next.</h2>{(user?.role==='verified'||user?.role==='admin')&&<PostForm kind="job" done={done}/>}<div className="listing">{jobs.map(j=><article key={j.id}><div><p className="eyebrow">{j.company} · {j.location}</p><h3>{j.title}</h3><p>{j.description}</p></div>{j.apply_url&&<a className="secondary" href={j.apply_url}>Apply</a>}</article>)}</div></section> }

function Events({events,user,done}:{events:Event[],user:User|null,done:()=>Promise<void>}) { return <section className="page"><p className="eyebrow">EVENTS</p><h2>Back to where it began.</h2>{(user?.role==='verified'||user?.role==='admin')&&<PostForm kind="event" done={done}/>}<div className="listing">{events.map(e=><article key={e.id}><div className="date">{new Date(e.starts_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</div><div><h3>{e.title}</h3><p>{e.venue}</p><p>{e.description}</p></div></article>)}</div></section> }

function PostForm({kind,done}:{kind:'job'|'event',done:()=>Promise<void>}) { const [show,setShow]=useState(false); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const body=Object.fromEntries(f); if(kind==='event')body.starts_at=new Date(String(body.starts_at)).toISOString();await api(`/${kind==='job'?'jobs':'events'}`,{method:'POST',body:JSON.stringify(body)});setShow(false);await done()}; const direct=kind==='job'; return <>{!show?<button className="secondary add" onClick={()=>setShow(true)}>{direct?'Post a job':'Submit an event'}</button>:<form className="form" onSubmit={submit}><input name="title" placeholder="Title" required/><textarea name="description" placeholder="Description" required/>{kind==='job'?<><input name="company" placeholder="Company" required/><input name="location" placeholder="Location" required/><input name="apply_url" placeholder="Application URL (optional)"/></>:<><input name="venue" placeholder="Venue" required/><input name="starts_at" type="datetime-local" required/></>}<button className="primary">{direct?'Publish job':'Submit for approval'}</button></form>}</> }

function Donate({user,note}:{user:User|null,note:(s:string)=>void}) { const [loading,setLoading]=useState(false); const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const f=new FormData(e.currentTarget); const amount=Number(f.get('amount')); setLoading(true); try { const out=await api('/donations/order',{method:'POST',body:JSON.stringify({amount,purpose:f.get('purpose')})}); if(out.provider==='demo') { note(`Demo donation of ₹${amount.toLocaleString()} recorded. Add Razorpay test keys to open hosted checkout.`); return } await loadRazorpayCheckout(); if(!window.Razorpay) throw new Error('Razorpay Checkout did not load. Please try again.'); const checkout=new window.Razorpay({key:out.key_id,amount:out.amount,currency:'INR',name:'TSEC Alumni Connect',description:String(f.get('purpose')),order_id:out.order_id,prefill:user?.email?{email:user.email}:undefined,theme:{color:'#5a345b'},handler:async(response:RazorpayResponse)=>{try { await api('/donations/verify',{method:'POST',body:JSON.stringify(response)}); note('Thank you — your test donation was verified.'); } catch(err) { note(err instanceof Error?err.message:'Payment verification failed.'); } }}); checkout.open(); } catch(err) { note(err instanceof Error?err.message:'Unable to start checkout.'); } finally { setLoading(false) } }; return <section className="donate"><p className="eyebrow">GIVE FORWARD</p><h2>Invest in a TSEC future.</h2><p className="lead">Every contribution helps students access opportunity, mentorship, and a stronger engineering education.</p><form className="donate-form" onSubmit={submit}><label>Amount (₹)<input name="amount" type="number" min="100" defaultValue="1000" required/></label><label>Purpose<input name="purpose" defaultValue="Student innovation fund" required/></label><button className="primary" disabled={loading}>{loading?'Opening checkout…':'Continue to secure checkout'}</button><small>Razorpay test mode · no real money is collected in this demo</small></form></section> }

function SignIn({after}:{after:()=>Promise<void>}) { const demo=async(email:string)=>{await api('/auth/demo-login?email='+encodeURIComponent(email),{method:'POST'});await after()}; return <section className="signin"><ShieldCheck/><p className="eyebrow">WELCOME TO THE COMMUNITY</p><h2>Sign in to participate.</h2><p>Use your Google or Microsoft account. New alumni accounts are reviewed by the TSEC admin team.</p><a className="oauth" href="/api/auth/google">Continue with Google</a><a className="oauth" href="/api/auth/microsoft">Continue with Microsoft</a><div className="demo"><b>Judging demo</b><p>Provider keys not configured? Explore seeded roles.</p><button onClick={()=>demo('riya.mehta@example.com')}>Sign in as verified alum</button><button onClick={()=>demo('admin@tsec.edu')}>Sign in as admin</button></div></section> }

function ContactModal({person,user,close,note}:{person:User,user:User|null,close:()=>void,note:(x:string)=>void}) { const [text,setText]=useState('');const ok=user?.role==='verified'||user?.role==='admin'; const send=async(e:FormEvent)=>{e.preventDefault();await api('/contact-requests',{method:'POST',body:JSON.stringify({recipient_id:person.id,message:text})});note('Connection request sent.');close()};return <div className="overlay"><div className="modal"><button className="close" onClick={close}><X/></button><div className="avatar">{person.name.split(' ').map(n=>n[0]).join('')}</div><h2>{person.name}</h2><p>{person.title} at {person.company}</p>{person.bio&&<p>{person.bio}</p>}{ok?<><p className="email"><Mail/> {person.email}</p><form className="form" onSubmit={send}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Introduce yourself and say why you'd like to connect." required/><button className="primary">Send connection request</button></form></>:<p className="lock">Sign in as a verified alum to see contact details and send a request.</p>}</div></div> }

type ReviewUser = User & { created_at:string }
type ReviewEvent = Event & { created_at:string; author?:{id:number;name:string;email:string}|null }

function Admin({user,done,note}:{user:User|null,done:()=>Promise<void>,note:(s:string)=>void}) { const [data,setData]=useState<{users:ReviewUser[];events:ReviewEvent[]}>(); const refresh=async()=>setData(await api('/admin/pending')); useEffect(()=>{if(user?.role==='admin')refresh().catch(e=>note(e.message))},[user]); const act=async(path:string,label:string)=>{await api(path,{method:'POST'});await refresh();await done();note(label)}; if(user?.role!=='admin')return <section className="page"><h2>Admin access required.</h2></section>; return <section className="page admin-page"><p className="eyebrow">ADMIN DASHBOARD</p><h2>Community stewardship.</h2><p className="admin-intro">Review alumni profiles and community events with the context needed to make a confident decision.</p>{!data?<p>Loading review queues…</p>:<><div className="admin-summary"><article><b>{data.users.length}</b><span>Alumni awaiting review</span></article><article><b>{data.events.length}</b><span>Events awaiting review</span></article></div><div className="admin-queues"><ReviewQueue title="Alumni verification" subtitle="Confirm new community members before they can participate." rows={data.users} kind="user" onAction={act}/><ReviewQueue title="Event moderation" subtitle="Review event details before publishing them to the community." rows={data.events} kind="event" onAction={act}/></div></>}</section> }

function ReviewQueue({title,subtitle,rows,kind,onAction}:{title:string;subtitle:string;rows:(ReviewUser|ReviewEvent)[];kind:'user'|'event';onAction:(path:string,label:string)=>Promise<void>}) { return <article className="review-queue"><div className="queue-heading"><div><p className="eyebrow">{rows.length} PENDING</p><h3>{title}</h3><p>{subtitle}</p></div></div>{rows.length?rows.map(row=><ReviewCard key={row.id} row={row} kind={kind} onAction={onAction}/>):<div className="queue-empty">Nothing is waiting for review.</div>}</article> }

function ReviewCard({row,kind,onAction}:{row:ReviewUser|ReviewEvent;kind:'user'|'event';onAction:(path:string,label:string)=>Promise<void>}) { const [open,setOpen]=useState(false); const isUser=kind==='user'; const userRow=row as ReviewUser, eventRow=row as ReviewEvent; const decide=async(decision:string)=>{const label=decision==='rejected'?'Rejected and removed from the queue.':isUser?'Alumnus verified.':'Event approved and published.'; if(decision==='rejected'&&!window.confirm(`Reject this ${isUser?'alumnus':'event'}? This cannot be undone from the review queue.`))return; await onAction(isUser?`/admin/users/${row.id}/${decision}`:`/admin/events/${row.id}/${decision}`,label)}; return <div className="review-card"><button className="review-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}><div><b>{isUser?userRow.name:eventRow.title}</b><span>{isUser?userRow.email:`${eventRow.venue} · ${new Date(eventRow.starts_at).toLocaleDateString()}`}</span></div>{open?<ChevronUp/>:<ChevronDown/>}</button>{open&&<div className="review-detail">{isUser?<><div className="detail-grid"><span><b>Graduation</b>{userRow.graduation_year||'Not provided'}</span><span><b>Branch</b>{userRow.branch||'Not provided'}</span><span><b>Role</b>{userRow.title||'Not provided'}</span><span><b>Company</b>{userRow.company||'Not provided'}</span><span><b>Location</b>{userRow.location||'Not provided'}</span><span><b>LinkedIn</b>{userRow.linkedin||'Not provided'}</span></div>{userRow.skills&&<p><b>Skills</b>{userRow.skills}</p>}{userRow.bio&&<p><b>Bio</b>{userRow.bio}</p>}</>:<><div className="detail-grid"><span><b>When</b>{new Date(eventRow.starts_at).toLocaleString()}</span><span><b>Where</b>{eventRow.venue}</span><span><b>Submitted by</b>{eventRow.author?`${eventRow.author.name} · ${eventRow.author.email}`:'Unknown'}</span></div><p><b>Description</b>{eventRow.description}</p></>}<div className="review-actions"><button className="reject" onClick={()=>decide('rejected')}>Reject</button><button className="primary" onClick={()=>decide(isUser?'verified':'approved')}>Approve</button></div></div>}</div> }

createRoot(document.getElementById('root')!).render(<App />)
